// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBufObject.proto

#ifndef PROTOBUF_INCLUDED_ProtoBufObject_2eproto
#define PROTOBUF_INCLUDED_ProtoBufObject_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ProtoBufObject_2eproto 

namespace protobuf_ProtoBufObject_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ProtoBufObject_2eproto
class ProtoBufObject;
class ProtoBufObjectDefaultTypeInternal;
extern ProtoBufObjectDefaultTypeInternal _ProtoBufObject_default_instance_;
namespace google {
namespace protobuf {
template<> ::ProtoBufObject* Arena::CreateMaybeMessage<::ProtoBufObject>(Arena*);
}  // namespace protobuf
}  // namespace google

enum ProtoBufObject_Type {
  ProtoBufObject_Type_CENSOR = 0,
  ProtoBufObject_Type_COMMAND = 1,
  ProtoBufObject_Type_LOG = 2
};
bool ProtoBufObject_Type_IsValid(int value);
const ProtoBufObject_Type ProtoBufObject_Type_Type_MIN = ProtoBufObject_Type_CENSOR;
const ProtoBufObject_Type ProtoBufObject_Type_Type_MAX = ProtoBufObject_Type_LOG;
const int ProtoBufObject_Type_Type_ARRAYSIZE = ProtoBufObject_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* ProtoBufObject_Type_descriptor();
inline const ::std::string& ProtoBufObject_Type_Name(ProtoBufObject_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    ProtoBufObject_Type_descriptor(), value);
}
inline bool ProtoBufObject_Type_Parse(
    const ::std::string& name, ProtoBufObject_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ProtoBufObject_Type>(
    ProtoBufObject_Type_descriptor(), name, value);
}
// ===================================================================

class ProtoBufObject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoBufObject) */ {
 public:
  ProtoBufObject();
  virtual ~ProtoBufObject();

  ProtoBufObject(const ProtoBufObject& from);

  inline ProtoBufObject& operator=(const ProtoBufObject& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoBufObject(ProtoBufObject&& from) noexcept
    : ProtoBufObject() {
    *this = ::std::move(from);
  }

  inline ProtoBufObject& operator=(ProtoBufObject&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoBufObject& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoBufObject* internal_default_instance() {
    return reinterpret_cast<const ProtoBufObject*>(
               &_ProtoBufObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProtoBufObject* other);
  friend void swap(ProtoBufObject& a, ProtoBufObject& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoBufObject* New() const final {
    return CreateMaybeMessage<ProtoBufObject>(NULL);
  }

  ProtoBufObject* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoBufObject>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoBufObject& from);
  void MergeFrom(const ProtoBufObject& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoBufObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ProtoBufObject_Type Type;
  static const Type CENSOR =
    ProtoBufObject_Type_CENSOR;
  static const Type COMMAND =
    ProtoBufObject_Type_COMMAND;
  static const Type LOG =
    ProtoBufObject_Type_LOG;
  static inline bool Type_IsValid(int value) {
    return ProtoBufObject_Type_IsValid(value);
  }
  static const Type Type_MIN =
    ProtoBufObject_Type_Type_MIN;
  static const Type Type_MAX =
    ProtoBufObject_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    ProtoBufObject_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return ProtoBufObject_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return ProtoBufObject_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return ProtoBufObject_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // required uint32 type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // required uint32 data = 3;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  ::google::protobuf::uint32 data() const;
  void set_data(::google::protobuf::uint32 value);

  // required float timestamp = 4;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 4;
  float timestamp() const;
  void set_timestamp(float value);

  // @@protoc_insertion_point(class_scope:ProtoBufObject)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_type();
  void clear_has_type();
  void set_has_data();
  void clear_has_data();
  void set_has_timestamp();
  void clear_has_timestamp();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 data_;
  float timestamp_;
  friend struct ::protobuf_ProtoBufObject_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtoBufObject

// required uint32 id = 1;
inline bool ProtoBufObject::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoBufObject::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoBufObject::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoBufObject::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 ProtoBufObject::id() const {
  // @@protoc_insertion_point(field_get:ProtoBufObject.id)
  return id_;
}
inline void ProtoBufObject::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:ProtoBufObject.id)
}

// required uint32 type = 2;
inline bool ProtoBufObject::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoBufObject::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoBufObject::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoBufObject::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 ProtoBufObject::type() const {
  // @@protoc_insertion_point(field_get:ProtoBufObject.type)
  return type_;
}
inline void ProtoBufObject::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:ProtoBufObject.type)
}

// required uint32 data = 3;
inline bool ProtoBufObject::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtoBufObject::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProtoBufObject::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProtoBufObject::clear_data() {
  data_ = 0u;
  clear_has_data();
}
inline ::google::protobuf::uint32 ProtoBufObject::data() const {
  // @@protoc_insertion_point(field_get:ProtoBufObject.data)
  return data_;
}
inline void ProtoBufObject::set_data(::google::protobuf::uint32 value) {
  set_has_data();
  data_ = value;
  // @@protoc_insertion_point(field_set:ProtoBufObject.data)
}

// required float timestamp = 4;
inline bool ProtoBufObject::has_timestamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtoBufObject::set_has_timestamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProtoBufObject::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProtoBufObject::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline float ProtoBufObject::timestamp() const {
  // @@protoc_insertion_point(field_get:ProtoBufObject.timestamp)
  return timestamp_;
}
inline void ProtoBufObject::set_timestamp(float value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:ProtoBufObject.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ProtoBufObject_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ProtoBufObject_Type>() {
  return ::ProtoBufObject_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ProtoBufObject_2eproto
